services:

  backend:
    build: .
    container_name: speech_backend

    ports:
      - "8000:8000"

    volumes:
      - .:/app
      - whisper_cache:/root/.cache/whisper

    environment:
      WHISPER_MODEL: ${WHISPER_MODEL:-base.en}
      GEMINI_API_KEY: ${GEMINI_API_KEY}

    depends_on:
      - db

  db:
    image: postgres:15

    container_name: speech_db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: speech_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  whisper_cache:
